const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpeg",
      price: "120",
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpeg",
      price: "90",
      countInStock: 20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpeg",
      price: "100",
      countInStock: 0,
      brand: "Lacoste",
      rating: 3.5,
      numReviews: 90,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p4.jpeg",
      price: "140",
      brand: "Nike",
      rating: 2.5,
      numReviews: 50,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p5.jpeg",
      price: "120",
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 30,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Fit Pants",
      category: "Pants",
      image: "/images/p6.jpeg",
      price: "100",
      countInStock: 0,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 100,
      description: "high quality product",
    },
  ],
};

export default data;
